server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

cloud:
  aws:
    credentials:
      accessKey: "AKIAT57SU3ZGBWSKIT6F"
      secretKey: "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"
    s3:
      bucket: "dangdo"
    region:
      static: "ap-northeast-2"
    stack:
      auto: false



spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .mustache
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DANGDO?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: fb1e726bb1c163f298c4ba23a8a15bdd
            client-secret: 7alWwq93CPo88QcTxcDOr2nQJReMXrnO
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            client-authentication-method: POST
        provider :
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jpa:
    hibernate: # hibernate 사용 설정
      # 애플리케이션 실행 시점에 테이블을 다 지우고, 내가 가진 entity 정보를 보고 다시 테이블 자동 생성
      # if exists drop table 해주고 다시 만들어준다고 보면 된다.
      ddl-auto: update
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: true

# 로그 레벨 설정
logging:
  level:
    # hibernate 가 남기는 모든 로그가 debug모드로 설정
    # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정
    org.springframework.web.client.RestTemplate: DEBUG

app:
  cors:
    allowedOrigins: http://localhost:3000, https://dnd-dangdo.netlify.app/
  # 토큰 관련 secret Key 및 RedirectUri 설정
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect
# jwt secret key 설정
jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

